{
 "title": "Klipper Dashboard",
 "tags": [
  "sonic pad",
  "Klipper",
  "moonraker",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(klipper_system_cpu, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_print_time / 60 / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Print", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$current_layer * 100 / $total_layers",
     "type": "math"
    }
   ]
  },
  {
   "title": "Layers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 2, "y": 9 },
   "targets": [
    {
     "expression": "($object_height - $first_layer_height) / $layer_height + 1",
     "type": "math"
    },
    {
     "expression": "($position_z - $first_layer_height) / $layer_height + 1",
     "type": "math"
    }
   ]
  },
  {
   "title": "Extruder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_extruder_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "power"
    },
    {
     "expr": "klipper_extruder_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "klipper_extruder_target{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "target"
    },
    {
     "expr": "klipper_fan_speed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "fan speed"
    }
   ]
  },
  {
   "title": "Heated Bed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_heater_bed_power{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "power"
    },
    {
     "expr": "klipper_heater_bed_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "klipper_heater_bed_target{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "target"
    }
   ]
  },
  {
   "title": "Hotend",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_extruder_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed Heater",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_heater_bed_temperature{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Klipper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_cpu_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "klipper_moonraker_cpu_usage{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_system_cpu{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "klipper_system_cpu_temp{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(klipper_network_rx_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": " {{interface}} klipper_network_rx_bytes"
    },
    {
     "expr": "rate(klipper_network_tx_bytes{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}} klipper_network_tx_bytes "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_memory_used{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}